version: "3"
services:
  front:
    build: .
    container_name: pybotters-dealer-front
    hostname: pybotters-dealer-front
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - FASTAPI_URL=http://pybotters-dealer-back:8000
    volumes:
      - type: bind
        source: ./nuxt
        target: /opt/nuxt
    working_dir: /opt/nuxt
    entrypoint: >
      bash -c 'yarn && yarn dev'
  back:
    build: .
    container_name: pybotters-dealer-back
    hostname: pybotters-dealer-back
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - type: bind
        source: ./python
        target: /opt/nuxt/python
      - type: bind
        source : ./apis.json
        target : /apis.json
    working_dir: /opt/nuxt/python
    environment:
      - PYBOTTERS_APIS=/apis.json
    entrypoint: >
      python -m uvicorn server:app --host 0.0.0.0 --port 8000

#    entrypoint: >
#      bash -c 'yarn add nuxt && yarn dev'
